### ISSUE TITLE
test flake: olm startup

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#839]
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pmem-csi/branches/PR-836/runs/1/nodes/90/steps/142/log/?start=0

```
[2020-12-18T11:38:27.682Z] Dec 18 11:38:27.410: FAIL: create operator deployment: "olm"
[2020-12-18T11:38:27.682Z] Unexpected error:
[2020-12-18T11:38:27.682Z]     <*errors.errorString | 0xc002faeb70>: {
[2020-12-18T11:38:27.682Z]         s: "command \"test/start-operator.sh -olm\" failed: exit status 1\nOutput: + echo 'Starting the operator using OLM....'\nStarting the operator using OLM....\n+ CATALOG_DIR=/mnt/workspace/pmem-csi_PR-836/deploy/olm-catalog\n+ BINDIR=/mnt/workspace/pmem-csi_PR-836/_work/bin\n+ '[' '!' -d /mnt/workspace/pmem-csi_PR-836/deploy/olm-catalog ']'\n+ set +e\n++ /mnt/workspace/pmem-csi_PR-836/_work/govm/ssh.0 kubectl get deployment pmem-csi-operator\n+ oupput='Error from server (NotFound): deployments.apps \"pmem-csi-operator\" not found'\n+ '[' 1 -eq 0 ']'\n+ echo Error from server '(NotFound):' deployments.apps '\"pmem-csi-operator\"' not found\n+ grep -q -v '(NotFound)'\n+ set -e\n++ mktemp -d\n+ tmpdir=/tmp/tmp.9lxNONUBw7\n+ TMP_CATALOG_DIR=/tmp/tmp.9lxNONUBw7/olm-catalog\n+ trap 'rm -rf $tmpdir' SIGTERM SIGINT EXIT\n+ cp -r /mnt/workspace/pmem-csi_PR-836/deploy/olm-catalog /tmp/tmp.9lxNONUBw7/\n++ grep currentCSV: /tmp/tmp.9lxNONUBw7/olm-catalog/pmem-csi-operator.package.yaml\n++ sed -r 's|.*v([0-9]+\\.[0-9]+\\.[0-9]+)$|\\1|'\n+ VERSION=0.8.0\n+ CSV_FILE=/tmp/tmp.9lxNONUBw7/olm-catalog/0.8.0/pmem-csi-operator.clusterserviceversion.yaml\n+ '[' 172.17.0.1:5000 '!=' '' ']'\n+ sed -i -e 's^intel/pmem-csi-driver:v0.8.0^172.17.0.1:5000/pmem-csi-driver:canary^g' /tmp/tmp.9lxNONUBw7/olm-catalog/0.8.0/pmem-csi-operator.clusterserviceversion.yaml\n+ '[' IfNotPresent '!=' '' ']'\n+ sed -i -e 's^imagePullPolicy:.IfNotPresent^imagePullPolicy: IfNotPresent^g' /tmp/tmp.9lxNONUBw7/olm-catalog/0.8.0/pmem-csi-operator.clusterserviceversion.yaml\n+ '[' olm '!=' '' ']'\n+ sed -i -r '/labels:$/{N; s|(\\n\\s+)(.*)|\\1pmem-csi.intel.com/deployment: olm\\1\\2| }' /tmp/tmp.9lxNONUBw7/olm-catalog/0.8.0/pmem-csi-operator.clusterserviceversion.yaml\n+ NAMESPACE=\n+ '[' default '!=' '' ']'\n+ NAMESPACE='--namespace default'\n+ /mnt/workspace/pmem-csi_PR-836/_work/bin/operator-sdk run packagemanifests --version 0.8.0 --namespace default --install-mode OwnNamespace --timeout 3m /tmp/tmp.9lxNONUBw7/olm-catalog\ntime=\"2020-12-18T11:38:14Z\" level=info msg=\"Creating pmem-csi-operator registry\"\ntime=\"2020-12-18T11:38:14Z\" level=info msg=\"  Creating ConfigMap \\\"default/pmem-csi-operator-registry-manifests-package\\\"\"\ntime=\"2020-12-18T11:38:14Z\" level=info msg=\"  Creating ConfigMap \\\"default/pmem-csi-operator-registry-manifests-0-8-0\\\"\"\ntime=\"2020-12-18T11:38:14Z\" level=info msg=\"  Creating Deployment \\\"default/pmem-csi-operator-registry-server\\\"\"\ntime=\"2020-12-18T11:38:14Z\" level=info msg=\"  Creating Service \\\"default/pmem-csi-operator-registry-server\\\"\"\ntime=\"2020-12-18T11:38:14Z\" level=info msg=\"Waiting for Deployment \\\"default/pmem-csi-operator-registry-server\\\" rollout to complete\"\ntime=\"2020-12-18T11:38:14Z\" level=info msg=\"  Waiting for Deployment \\\"default/pmem-csi-operator-registry-server\\\" to rollout: 0 out of 1 new replicas have been updated\"\ntime=\"2020-12-18T11:38:15Z\" level=info msg=\"  Waiting for Deployment \\\"default/pmem-csi-operator-registry-server\\\" to rollout: 0 of 1 updated replicas are available\"\ntime=\"2020-12-18T11:38:24Z\" level=info msg=\"  Deployment \\\"default/pmem-csi-operator-registry-server\\\" successfully rolled out\"\ntime=\"2020-12-18T11:38:24Z\" level=info msg=\"Created CatalogSource: pmem-csi-operator-catalog\"\ntime=\"2020-12-18T11:38:24Z\" level=info msg=\"OperatorGroup \\\"operator-sdk-og\\\" created\"\ntime=\"2020-12-18T11:38:24Z\" level=info msg=\"Created Subscription: pmem-csi-operator-v0-8-0-sub\"\ntime=\"2020-12-18T11:38:27Z\" level=fatal msg=\"Failed to run packagemanifests: error approving install plan: Operation cannot be fulfilled on installplans.operators.coreos.com \\\"install-j8kf2\\\": the object has been modified; please apply your changes to the latest version and try again\\n\"\n+ rm -rf /tmp/tmp.9lxNONUBw7\n",
```

**Comment by avalluri** [comment]
With [this](https://github.com/operator-framework/operator-sdk/pull/4309) oprator-sdk PR and the supported [change](https://github.com/kubernetes/apimachinery/commit/fb0f31795c1a4c82d7f141959c0605bb5c18977f) in apimachinery got merged to v1.19 this OLM startup issue should not occur anymore.

**Comment by avalluri** [comment]
As in change #866, all the required changes are in place by moving to operator-sdk v1.3.0 should fix this issue.

**Comment by pohly** [comment]
> supported change in apimachinery got merged to v1.19

This comment confuses me - why does a change in Kubernetes matter  for this problem? Does that mean that this issue can still occur with older Kubernetes (1.17, 1.18)?

**Comment by avalluri** [comment]
>  why does a change in Kubernetes matter for this problem? 

Error unwrapping support for apimachinery's Is*Error() functions was added in 1.19. This is required for the operator-sdk.

> Does that mean that this issue can still occur with older Kubernetes (1.17, 1.18)?

No, those are client library changes.
